SOURCES=\
src/Cuboid.cpp\
src/outputWriter/XYZWriter.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/VTKWriter.cpp\
src/Particle.cpp\
src/tests/ParticleContainerTest.cpp\
src/tests/ParticleIteratorTest.cpp\
src/tests/ParticleGeneratorTest.cpp\
src/FileReader.cpp\
src/Sphere.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/MolSim.cpp\
src/utils/ParticleContainer.cpp\
src/utils/ParticleGenerator.cpp\
src/utils/ParticleIterator.cpp\
src/utils/InputSetting.cpp\
src/utils/InputParticles.cpp\
src/utils/InputSpheres.cpp\
src/utils/InputCuboids.cpp\
