/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <sstream>
#include <iostream>
#include <log4cxx/logger.h>
#include <log4cxx/propertyconfigurator.h>
#include <log4cxx/xml/domconfigurator.h>

log4cxx::LoggerPtr particlelogger(log4cxx::Logger::getLogger("particle"));

Particle::Particle(int type_arg) {
	type = type_arg;
	LOG4CXX_INFO(particlelogger,"Arrived @ Type Constructor.");
	f = 0.0;
	old_f = 0.0;
}

Particle::Particle(const Particle& other) {
	x = other.x;
	v = other.v;
	f = other.f;
	old_f = other.old_f;
	temp_f = 0.0;
	m = other.m;
	type = other.type;
	LOG4CXX_TRACE(particlelogger,"Particle generated by copy!");
}

// Todo: maybe use initializater list instead of copy?
Particle::Particle(	utils::Vector<double, 3> x_arg,
	        utils::Vector<double, 3> v_arg,
	        double m_arg,
	        int type_arg
) {
    x = x_arg;
    v = v_arg;
    m = m_arg;
    type = type_arg;
    f = 0.0;
    old_f = 0.0;
    LOG4CXX_TRACE(particlelogger,"Particle generated!");
}

Particle::~Particle() {
	LOG4CXX_TRACE(particlelogger,"Particle destructed!");
}

utils::Vector<double, 3>& Particle::getX() {
	return x;
}

utils::Vector<double, 3>& Particle::getV() {
	return v;
}

utils::Vector<double, 3>& Particle::getF() {
	return f;
}

utils::Vector<double, 3>& Particle::getOldF() {
	return old_f;
}

double& Particle::getM() {
	return m;
}

utils::Vector<double, 3> Particle::getTempF(){
	return temp_f;
}

void Particle::updateTempF(utils::Vector<double, 3> newF) {
	temp_f = temp_f + newF;
}

int& Particle::getType() {
	return type;
}

void Particle::setF(utils::Vector<double, 3> newF){
	old_f = f;
	f = newF;
}

void Particle::deleteTempF(){
	temp_f = 0.0;
}

std::string Particle::toString() {
	std::stringstream stream;
	stream << "Particle: X:" << x <<  " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
	return stream.str();
}

bool Particle::operator ==(Particle& other) {
	if ( (x == other.x) && (v == other.v) && (f == other.f) &&
			(type == other.type) & (m == other.m) && (old_f == other.old_f)) {
		return true;
	}

	return false;
}

std::ostream& operator<<(std::ostream& stream, Particle& p) {
	stream << p.toString();
	return stream;
}

std::list<Particle>& Particle::getDirectNeighbors(){
	return directNeighbors;
}

std::list<Particle>& Particle::getDiagNeighbors(){
	return diagNeighbors;
}

int& Particle::getID(){
	return ID;
}

bool Particle::isNeighborTo(Particle p){
	//ID is unique for each particle
	for (std::list<Particle>::iterator it = this->getDirectNeighbors().begin();
			it != this->getDirectNeighbors().end(); it++){
		if ((*it).getID() == p.getID())
			return true;
	}

	for (std::list<Particle>::iterator it = this->getDiagNeighbors().begin();
			it != this->getDiagNeighbors().end(); it++){
		if ((*it).getID() == p.getID())
			return true;
	}

	return false;
}
